### ISSUE TITLE
Can you explain this code?

### ISSUE THREAD

**Issue by SaikumarS2611** [SaikumarS2611/Pattern#7]
https://github.com/SaikumarS2611/Pattern/blob/ec017d01c4867e150ff6305f11c9d79e722ab3f8/numbers/eight.py#L6

**Comment by saribalarakeshreddy** [comment]
https://github.com/SaikumarS2611/Pattern/blob/ec017d01c4867e150ff6305f11c9d79e722ab3f8/numbers/eight.py#L6 he @charansaim1819  took one extra col value which is unnecessary and repeats one extra loop on an inner loop can result in some extra time to compile

**Comment by charansaim1819** [comment]
> https://github.com/SaikumarS2611/Pattern/blob/ec017d01c4867e150ff6305f11c9d79e722ab3f8/numbers/eight.py#L6
> 
> he @charansaim1819 took one extra col value which is unnecessary and repeats one extra loop on an inner loop can result in some extra time to compile

https://github.com/SaikumarS2611/Pattern/blob/e145056d232a631821c2504be2d07d9f8ad35e90/numbers/eight.py#L5


i have fixed this problem by taking the number of as much as we required

 if you are ok with this or else want any information about this code qoute reply below. otherwise i will close this issue

**Comment by charansaim1819** [comment]
> https://github.com/SaikumarS2611/Pattern/blob/ec017d01c4867e150ff6305f11c9d79e722ab3f8/numbers/eight.py#L6
if col in(1,2) and row%3==0 or col%3==0 and row%3!=0 : 

i have taken 7 rows and 4 columns for printing number 8 the  above code will resemble the following result 
  
![image](https://user-images.githubusercontent.com/80595802/111779824-993c9880-88dc-11eb-947e-874b2816076b.png)
the first condition  col in(1,2) and row%3==0 prints the horizontal two starred lines at rows 0,3,6 and second condition col%3==0 and row%3!=0 prints vertical  starred lines where horizontal lines don't came in columns 0,3

**Comment by SaikumarS2611** [comment]
Yaa good
